### ISSUE TITLE
Add Pagination to the Challenge Listing Page

### ISSUE THREAD

**Issue by dogukanteber** [OpenUnited/platform#130]
We currently show all of the challenges that exist in our platform. Since the number of challenges is not much, that wasn't a problem, until now. We need to add a pagination to the challenge listing page as the number of challenges is increasing.

**Comment by sachintom999** [comment]
@dogukanteber @adrianmcphee , 

Given the current listings below, are we planning to **paginate by 8 items?** 

![Screenshot at Oct 26 11-41-15](https://github.com/OpenUnited/platform/assets/62328681/b8e46880-42d4-4371-a02c-3f9f0068ec9f)

**Comment by dogukanteber** [comment]
Well, 8 is not a round number but that's all we have in the current situation. We may shorten the width of each card and remove some of the left and right margins but I am not sure if doing that looks good.

Let's paginate by 8 items per page. We'll see how it goes and make necessary update when necessary.

**Comment by sachintom999** [comment]
@dogukanteber, Okay. 

Can you assign this to me ?

**Comment by dogukanteber** [comment]
Sure!

**Comment by dogukanteber** [comment]
Done by #141
