### ISSUE TITLE
Add support for cookies to Sign In Page

### ISSUE THREAD

**Issue by dogukanteber** [OpenUnited/platform#139]
On the sign-in page, we have a label that says `Remember Me` but it does not have a checkbox next to it that remembers the user's login:

<img width="1511" alt="Screenshot 2023-10-27 at 11 36 27" src="https://github.com/OpenUnited/platform/assets/47397379/56ba3173-0a80-4398-8274-721bdea68347">

Currently, the sign-in user keeps signed in unless he/she logs out from the account. We need to enable this `Remember Me` checkbox and if it's checked, we keep the user logged in for 30 days. Otherwise, we should necessitate to log in.

**Comment by sachintom999** [comment]
@dogukanteber please assign this to me

**Comment by dogukanteber** [comment]
Closed by #160
