### ISSUE TITLE
Is htmx in use?

### ISSUE THREAD

**Issue by frederikhors** [OpenUnited/platform#348]
Hello all beautiful people,

after reading [this article](https://htmx.org/essays/another-real-world-react-to-htmx-port) I went to [your site](https://openunited.com/) and browsing (with Chrome 128) I don't see htmx working.

Every link is loaded from scratch.

Have you given up using htmx?

**Comment by adrianmcphee** [comment]
Hi @frederikhors , yes we're using HTMX... e.g. https://github.com/search?q=repo%3AOpenUnited%2Fplatform+hx-get&type=code and https://github.com/search?q=repo%3AOpenUnited%2Fplatform%20hx-post&type=code

here's some hyperscript for you too: https://github.com/OpenUnited/platform/blob/a5efd385cde31b79fb94f3d0ec088bfb2c329019/apps/talent/templates/talent/partials/star_rating.html#L4

https://github.com/OpenUnited/platform/blob/main/apps/templates/base_html.html#L45
